export const large = '@media (min-width: 1200px)'
export const iPadPro = '@media (min-width: 1024px) and (max-width: 1199px)'
export const iPadandMini = '@media (min-width: 768px) and (max-width: 1023px)'
export const iPhone14Pro = '@media (min-width: 430px) and (max-width: 767px)'
export const iPhoneXR_6Plus_7Plus_8Plus = '@media (min-width: 414px) and (max-width: 429px)'
export const iPhone12Pro = '@media (min-width: 390px) and (max-width: 413px)'
export const iPhoneSE_6_7_8_andX = '@media (min-width: 375px) and (max-width: 389px)'
export const iPhone4_and5SE = '@media (min-width: 320px) and (max-width: 374px)'